### PR TITLE
migrating WakaTime for Notepad++ to WakaTime# (WakaTime Sharp)

### PR DESCRIPTION
**Pull request by salaros**
- updated WakaTime# with the latest changes committed by @alanhamlett 
- used ILMerge to produce one .dll file (containing plugin definition + plugin dependencies including WakaTime#)

### CODE REVIEW

**Comment by salaros** [comment]
Hey, so what's up?

**Comment by gandarez** [comment]
We need to review it before accept the merge.

**Comment by salaros** [comment]
@alanhamlett I know this cannot be merged directly, but what about solving the only conflict and merge it, while there is only one conflict, later it will be much harder

**Comment by alanhamlett** [comment]
This is a good idea, but we need to make an official WakaTime C# library first and use it between all the C#-based extensions. That way our bug fixes will get propagated to all the extensions without needing a PR to the external WakaTime# repo.

**Comment by salaros** [comment]
Hi @alanhamlett, I think I can create a new pull request at this point and if it goes OK, I would like to do the same thing for VS and probably Unity

**Pull request closed without merging**
