### PR TITLE
x64 + appveyor CI

### LINKED ISSUE #19: Not compatible with NPP v7 64-bit

### PR DESCRIPTION
**Pull request by chcg**
- added x64 config and updated PluginInfrastructure to v0.93.96 to fix #19

- added appveyor config
, see https://ci.appveyor.com/project/chcg/notepadpp-wakatime/build/4.0.2.5

### CODE REVIEW

**Comment by alanhamlett** [comment]
Thanks!

**Comment by alanhamlett** [comment]
@chcg looks like we can use appveyor to build the plugin binary? Is there a convention for distributing Notepad++ plugins using appveyor?

**Comment by chcg** [comment]
@alanhamlett Yes you could use appveyor to build and also deploy the buildresult to github as releases. You need to register this project at appveyor and provide an auth_token, see

https://www.appveyor.com/docs/deployment/github/#provider-settings

for a howto. The appveyor.yml is prepared for that and just need the github token. With each git tag a release should happen then.

**Comment by chcg** [comment]
@alanhamlett There is no convention on using appveyor apart from convenience. Also automated releases via appveyor are possible so a release is just a tag away.
So local build are still ok. Building via appveyor or some other CI has the additional safety that your project is not just buildable on your dev computer but should be easily work also for others forking your repo.

Any plans to release a x64 version?

**Comment by alanhamlett** [comment]
@chcg yes, thanks for asking. I'm planning to fix the build for x32 and x64 this week. I noticed the x32 version from GH releases doesn't seem to work with the latest Notepad++ anymore.

**Pull request merged**
